name: llm-thesis
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - openpyxl
  - notebook
  - jupyter
  - scikit-learn
  - requests
  - tqdm
  - pip
  - pip:
      - tabulate
      - langchain
      - crewai
      - autogen
      - tinyllama
